/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Dell
 */
public class Manage_Categories extends javax.swing.JFrame {
    
    DefaultTableModel model;
    Category c;
    public Manage_Categories() {
        initComponents();
        FillingTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cat = new app.bolivia.swing.JCTextField();
        add1 = new rojerusan.RSMaterialButtonCircle();
        delete1 = new rojerusan.RSMaterialButtonCircle();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cat2 = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        sub1 = new app.bolivia.swing.JCTextField();
        jLabel8 = new javax.swing.JLabel();
        sub2 = new app.bolivia.swing.JCTextField();
        jLabel9 = new javax.swing.JLabel();
        sub3 = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        sub4 = new app.bolivia.swing.JCTextField();
        add2 = new rojerusan.RSMaterialButtonCircle();
        delete2 = new rojerusan.RSMaterialButtonCircle();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Cat = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        Back.setBackground(new java.awt.Color(204, 102, 255));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText("Back");

        javax.swing.GroupLayout BackLayout = new javax.swing.GroupLayout(Back);
        Back.setLayout(BackLayout);
        BackLayout.setHorizontalGroup(
            BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
        );
        BackLayout.setVerticalGroup(
            BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cat.setBackground(new java.awt.Color(102, 0, 102));
        cat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        cat.setForeground(new java.awt.Color(255, 255, 255));
        cat.setPlaceholder("Category");
        cat.setSelectionColor(new java.awt.Color(153, 153, 255));
        cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catActionPerformed(evt);
            }
        });

        add1.setBackground(new java.awt.Color(204, 102, 255));
        add1.setText("ADD");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });

        delete1.setBackground(new java.awt.Color(204, 102, 255));
        delete1.setText("DELETE");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Category Management");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("SubCategory Management");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Category");

        cat2.setBackground(new java.awt.Color(102, 0, 102));
        cat2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        cat2.setForeground(new java.awt.Color(255, 255, 255));
        cat2.setPlaceholder("Category");
        cat2.setSelectionColor(new java.awt.Color(153, 153, 255));
        cat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sub1");

        sub1.setBackground(new java.awt.Color(102, 0, 102));
        sub1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        sub1.setForeground(new java.awt.Color(255, 255, 255));
        sub1.setPlaceholder("Category");
        sub1.setSelectionColor(new java.awt.Color(153, 153, 255));
        sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sub2");

        sub2.setBackground(new java.awt.Color(102, 0, 102));
        sub2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        sub2.setForeground(new java.awt.Color(255, 255, 255));
        sub2.setPlaceholder("Category");
        sub2.setSelectionColor(new java.awt.Color(153, 153, 255));
        sub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sub3");

        sub3.setBackground(new java.awt.Color(102, 0, 102));
        sub3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        sub3.setForeground(new java.awt.Color(255, 255, 255));
        sub3.setPlaceholder("Category");
        sub3.setSelectionColor(new java.awt.Color(153, 153, 255));
        sub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sub4");

        sub4.setBackground(new java.awt.Color(102, 0, 102));
        sub4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        sub4.setForeground(new java.awt.Color(255, 255, 255));
        sub4.setPlaceholder("Category");
        sub4.setSelectionColor(new java.awt.Color(153, 153, 255));
        sub4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub4ActionPerformed(evt);
            }
        });

        add2.setBackground(new java.awt.Color(204, 102, 255));
        add2.setText("ADD");
        add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ActionPerformed(evt);
            }
        });

        delete2.setBackground(new java.awt.Color(204, 102, 255));
        delete2.setText("DELETE");
        delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(sub4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(sub2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(sub3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(delete2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(delete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cat2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cat2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sub1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(1, 1, 1)
                .addComponent(sub2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sub3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sub4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_View_Details_26px.png"))); // NOI18N
        jLabel2.setText("List of Categories");

        close.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        Table_Cat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "SubCategory1", "SubCategory2", "SubCategory3", "SubCategory4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table_Cat.setColorBackgoundHead(new java.awt.Color(153, 0, 153));
        Table_Cat.setColorFilasForeground1(new java.awt.Color(204, 0, 204));
        Table_Cat.setColorFilasForeground2(new java.awt.Color(204, 0, 204));
        Table_Cat.setColorSelBackgound(new java.awt.Color(204, 0, 204));
        Table_Cat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_CatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Cat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close)
                .addGap(39, 39, 39))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void Table_CatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_CatMouseClicked
        int rowNo = Table_Cat.getSelectedRow();
        TableModel model = Table_Cat.getModel();
        cat.setText(model.getValueAt(rowNo, 1).toString());
        sub1.setText(model.getValueAt(rowNo, 2).toString());
        sub2.setText(model.getValueAt(rowNo, 3).toString());
        sub3.setText(model.getValueAt(rowNo, 4).toString());
        sub4.setText(model.getValueAt(rowNo, 5).toString());
        
    }//GEN-LAST:event_Table_CatMouseClicked

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        if(!cat.getText().isEmpty())
        {
            try {
               
                Connection con =  DriverManager.getConnection("jdbc:derby://localhost:1527/Library", "user1", "123" );
                PreparedStatement pstm;
                int count = 0;
                String ID= cat.getText();
                String SQL="DELETE FROM Category WHERE Category = ?";
                pstm = con.prepareStatement(SQL);
                pstm.setString(1, ID);
                count = pstm.executeUpdate();
                con.close();
                if(count>0){
                    JOptionPane.showMessageDialog(this, "Deleted !", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
                else{JOptionPane.showMessageDialog(this, "ID doesn't exist", "Execution Alert", JOptionPane.ERROR_MESSAGE);
                }
            }catch (SQLException ex) {
                Logger.getLogger(Manage_Librarians.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "ID must be filled!", "Execution Alert", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_delete1ActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        if(!cat.getText().isEmpty())
        {
            try {
                Connection con =  DriverManager.getConnection("jdbc:derby://localhost:1527/Library", "user1", "123" );
                PreparedStatement pstm;
                int count =0;
                String ID= cat.getText();
                String SQL= "INSERT INTO Category VALUES(?,?,?,?,?) ";
                pstm = con.prepareStatement(SQL);
                pstm.setString(1, cat.getText() );
                pstm.setString(2, "" );
                pstm.setString(3, "" );
                pstm.setString(4, "" );
                pstm.setString(5, "" );

                count = pstm.executeUpdate();

               
                
                con.close();
                if(count>0){
                    JOptionPane.showMessageDialog(this, "Inserted !", "Success", JOptionPane.INFORMATION_MESSAGE);
                }

            }catch (SQLException ex) {
                Logger.getLogger(Manage_Librarians.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(this, "Already exists !", "Success", JOptionPane.ERROR_MESSAGE);

            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Fields must be filled!", "Execution Alert", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_add1ActionPerformed

    private void catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked

        AdminDashboard Frame = new AdminDashboard() ;
        Frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void cat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cat2ActionPerformed

    private void sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub1ActionPerformed

    private void sub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub2ActionPerformed

    private void sub3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub3ActionPerformed

    private void sub4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub4ActionPerformed

    private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed
        if(!cat2.getText().isEmpty() && (!sub1.getText().isEmpty() || !sub2.getText().isEmpty() ||!sub3.getText().isEmpty() || !sub4.getText().isEmpty() ))
        {
            try {
                c = new Category(cat2.getText());
                
                Connection con =  DriverManager.getConnection("jdbc:derby://localhost:1527/Library", "user1", "123" );
                PreparedStatement pstm;
                int count =0;
                String ID= cat2.getText();
               
                if (!sub1.getText().isEmpty()){
                String SQL= "Update Category SET SubCategory1= ? WHERE Category = '" + ID + "'";
                pstm = con.prepareStatement(SQL);
                pstm.setString(1, sub1.getText() );
                count = pstm.executeUpdate();

                }
                if (!sub2.getText().isEmpty()){
                String SQL= "Update Category SET SubCategory2= ? WHERE Category = '" + ID  + "'";
                pstm = con.prepareStatement(SQL);
                pstm.setString(1, sub2.getText() );
                count = pstm.executeUpdate();

                }
                if (!sub3.getText().isEmpty()){
                String SQL= "Update Category SET SubCategory3= ? WHERE Category = '" + ID  + "'";
                pstm = con.prepareStatement(SQL);
                pstm.setString(1, sub3.getText() );
                count = pstm.executeUpdate();

                }
                if (!sub4.getText().isEmpty()){
                String SQL= "Update Category SET SubCategory4= ? WHERE Category = '" + ID + "'";
                pstm = con.prepareStatement(SQL);
                pstm.setString(1, sub4.getText() );
                count = pstm.executeUpdate();

                }
                
                con.close();
                if(count>0){
                    JOptionPane.showMessageDialog(this, "Inserted !", "Success", JOptionPane.INFORMATION_MESSAGE);
                }

            }catch (SQLException ex) {
                Logger.getLogger(Manage_Librarians.class.getName()).log(Level.SEVERE, null, ex);

            }
        } 
        else {
            JOptionPane.showMessageDialog(this, "Fill at least one subcategory!", "Execution Alert", JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_add2ActionPerformed

    private void delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete2ActionPerformed
        if(!cat2.getText().isEmpty() && (!sub1.getText().isEmpty() || !sub2.getText().isEmpty() ||!sub3.getText().isEmpty() || !sub4.getText().isEmpty() ))
        {
            try {
                c = new Category(cat2.getText());
                
                Connection con =  DriverManager.getConnection("jdbc:derby://localhost:1527/Library", "user1", "123" );
                PreparedStatement pstm;
                int count =0;
                String ID= cat2.getText();
               
                if (!sub1.getText().isEmpty()){
                String SQL= "Update Category SET SubCategory1= ? WHERE Category = '" + ID + "'";
                pstm = con.prepareStatement(SQL);
                pstm.setString(1, "");
                count = pstm.executeUpdate();

                }
                if (!sub2.getText().isEmpty()){
                String SQL= "Update Category SET SubCategory2= ? WHERE Category = '" + ID  + "'";
                pstm = con.prepareStatement(SQL);
                pstm.setString(1, "" );
                count = pstm.executeUpdate();

                }
                if (!sub3.getText().isEmpty()){
                String SQL= "Update Category SET SubCategory3= ? WHERE Category = '" + ID  + "'";
                pstm = con.prepareStatement(SQL);
                pstm.setString(1, "" );
                count = pstm.executeUpdate();

                }
                if (!sub4.getText().isEmpty()){
                String SQL= "Update Category SET SubCategory4= ? WHERE Category = '" + ID + "'";
                pstm = con.prepareStatement(SQL);
                pstm.setString(1, "" );
                count = pstm.executeUpdate();

                }
                
                con.close();
                if(count>0){
                    JOptionPane.showMessageDialog(this, "Deleted !", "Success", JOptionPane.INFORMATION_MESSAGE);
                }

            }catch (SQLException ex) {
                Logger.getLogger(Manage_Librarians.class.getName()).log(Level.SEVERE, null, ex);

            }
        } 
        else {
            JOptionPane.showMessageDialog(this, "Fill at least one subcategory!", "Execution Alert", JOptionPane.ERROR_MESSAGE);
        }                         
    }//GEN-LAST:event_delete2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Categories().setVisible(true);
            }
        });
    }
    
    
    public void FillingTable(){
    
         try {
          
            Connection con =  DriverManager.getConnection("jdbc:derby://localhost:1527/Library", "user1", "123" );
            String SQL = "SELECT * FROM Category" ;  
            Statement stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ResultSet rs=stmt.executeQuery(SQL);  
            
            while(rs.next()){
                String ID= rs.getString("Category");
                String sub1 = rs.getString("SubCategory1");
                String sub2 = rs.getString("SubCategory2");
                String sub3 = rs.getString("SubCategory3");
                String sub4= rs.getString("SubCategory4");
               
                
                Object[] obj = {ID,sub1,sub2,sub3,sub4};
                model = (DefaultTableModel) Table_Cat.getModel();
                model.addRow(obj);
            
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Display_Students.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Back;
    private rojerusan.RSTableMetro Table_Cat;
    private rojerusan.RSMaterialButtonCircle add1;
    private rojerusan.RSMaterialButtonCircle add2;
    private app.bolivia.swing.JCTextField cat;
    private app.bolivia.swing.JCTextField cat2;
    private javax.swing.JLabel close;
    private rojerusan.RSMaterialButtonCircle delete1;
    private rojerusan.RSMaterialButtonCircle delete2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private app.bolivia.swing.JCTextField sub1;
    private app.bolivia.swing.JCTextField sub2;
    private app.bolivia.swing.JCTextField sub3;
    private app.bolivia.swing.JCTextField sub4;
    // End of variables declaration//GEN-END:variables
}
