package Project;


import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;




public class Manage_Student extends javax.swing.JFrame {

    DefaultTableModel model;
    public Manage_Student() {
        initComponents();
        FillingTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new app.bolivia.swing.JCTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        email = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        phone = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        age = new app.bolivia.swing.JCTextField();
        Add_btn = new rojerusan.RSMaterialButtonCircle();
        modify_btn = new rojerusan.RSMaterialButtonCircle();
        jLabel11 = new javax.swing.JLabel();
        univ = new app.bolivia.swing.JCTextField();
        Delete = new rojerusan.RSMaterialButtonCircle();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Stud = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 102));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 0, 51));

        Back.setBackground(new java.awt.Color(0, 0, 0));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText("Back");

        javax.swing.GroupLayout BackLayout = new javax.swing.GroupLayout(Back);
        Back.setLayout(BackLayout);
        BackLayout.setHorizontalGroup(
            BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
        );
        BackLayout.setVerticalGroup(
            BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        id.setBackground(new java.awt.Color(102, 0, 51));
        id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setPlaceholder("Enter ID");
        id.setSelectionColor(new java.awt.Color(153, 153, 255));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name:");

        name.setBackground(new java.awt.Color(102, 0, 51));
        name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setPlaceholder("Enter name");
        name.setSelectionColor(new java.awt.Color(153, 153, 255));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email:");

        email.setBackground(new java.awt.Color(102, 0, 51));
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setPlaceholder("Email");
        email.setSelectionColor(new java.awt.Color(153, 153, 255));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/graduates (1).png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone Number :");

        phone.setBackground(new java.awt.Color(102, 0, 51));
        phone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setPlaceholder("(+216)");
        phone.setSelectionColor(new java.awt.Color(153, 153, 255));
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Age :");

        age.setBackground(new java.awt.Color(102, 0, 51));
        age.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setPlaceholder("Age");
        age.setSelectionColor(new java.awt.Color(153, 153, 255));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });

        Add_btn.setBackground(new java.awt.Color(0, 0, 0));
        Add_btn.setText("ADD");
        Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btnActionPerformed(evt);
            }
        });

        modify_btn.setBackground(new java.awt.Color(0, 0, 0));
        modify_btn.setText("MODIFY");
        modify_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modify_btnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("University :");

        univ.setBackground(new java.awt.Color(102, 0, 51));
        univ.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        univ.setForeground(new java.awt.Color(255, 255, 255));
        univ.setPlaceholder("University");
        univ.setSelectionColor(new java.awt.Color(153, 153, 255));
        univ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                univActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(0, 0, 0));
        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(univ, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modify_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addComponent(univ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modify_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(437, 437, 437))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_View_Details_26px.png"))); // NOI18N
        jLabel2.setText("List of Students");

        close.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        Table_Stud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Phone", "Age", "University"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table_Stud.setColorBackgoundHead(new java.awt.Color(0, 0, 0));
        Table_Stud.setColorFilasForeground1(new java.awt.Color(204, 0, 204));
        Table_Stud.setColorFilasForeground2(new java.awt.Color(204, 0, 204));
        Table_Stud.setColorSelBackgound(new java.awt.Color(204, 0, 204));
        Table_Stud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_StudMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Stud);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(close)
                .addGap(291, 291, 291))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1349, 716));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void Table_StudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_StudMouseClicked
       int rowNo = Table_Stud.getSelectedRow();
       TableModel model = Table_Stud.getModel();
       id.setText(model.getValueAt(rowNo, 0).toString());
       name.setText(model.getValueAt(rowNo, 1).toString());
       email.setText(model.getValueAt(rowNo, 2).toString());
       phone.setText(model.getValueAt(rowNo, 3).toString());
       age.setText(model.getValueAt(rowNo, 4).toString());
       univ.setText(model.getValueAt(rowNo, 5).toString());
     
    }//GEN-LAST:event_Table_StudMouseClicked

    private void modify_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modify_btnActionPerformed
    Student stud = new Student();
        
        if(!id.getText().isEmpty() && !name.getText().isEmpty() && !email.getText().isEmpty() && !phone.getText().isEmpty()  &&!age.getText().isEmpty() && !univ.getText().isEmpty())
        {if(stud.validateEmail(email.getText()))  {
            try {
                PreparedStatement pstm;
                int count;

                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Library", "user1", "123" );
                count = 0;
                int ID= Integer.parseInt(id.getText());
                String Name = name.getText();
                String Email = email.getText();
                String Phone = phone.getText();
                int Age= Integer.parseInt(age.getText());
                 String university = univ.getText();
                 
                String SQL= "UPDATE Students SET Stud_ID=?,Stud_Name=?,Stud_Email=?,Stud_Phone=?,Stud_Age=?,Stud_University=? WHERE Stud_ID=?";
                pstm = con.prepareStatement(SQL);
                pstm.setInt(1, ID);
                pstm.setString(2, Name);
                pstm.setString(3, Email);
                pstm.setString(4, Phone);
                pstm.setInt(5, Age);
                pstm.setString(6, university);
                pstm.setInt(7,ID);

                count = pstm.executeUpdate();
                if(count>0){
                    JOptionPane.showMessageDialog(this, "Updated !", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
                else {
                    JOptionPane.showMessageDialog(this, "ID doesn't exist", "Execution Alert", JOptionPane.ERROR_MESSAGE);
                }

            }catch (SQLException ex) {
                Logger.getLogger(Manage_Librarians.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
          
          else {JOptionPane.showMessageDialog(this, "Email not valid!", "Execution Alert", JOptionPane.ERROR_MESSAGE);}
        }else {
            JOptionPane.showMessageDialog(this, "Fields must be filled!", "Execution Alert", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_modify_btnActionPerformed

    private void Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btnActionPerformed
        
        Student stud = new Student();
        
        if(!id.getText().isEmpty() && !name.getText().isEmpty() && !email.getText().isEmpty() && !phone.getText().isEmpty()  &&!age.getText().isEmpty() && !univ.getText().isEmpty())
          if(stud.validateEmail(email.getText()))  {
            try {
                Connection con =  DriverManager.getConnection("jdbc:derby://localhost:1527/Library", "user1", "123" );
                PreparedStatement pstm;
                int count =0;
                int ID= Integer.parseInt(id.getText());
                String Name = name.getText();
                String Email = email.getText();
                String university = univ.getText();
                String Phone = phone.getText();
                int Age= Integer.parseInt(age.getText());
                

                String SQL= "INSERT INTO Students VALUES(?,?,?,?,?,?,?)";

                pstm = con.prepareStatement(SQL);
                pstm.setInt(1, ID);
                pstm.setString(2, Name);
                pstm.setString(3, Email);
                pstm.setString(4, Phone);
                pstm.setInt(5, Age);
                pstm.setString(6, university);
               pstm.setInt(7, 0);
               
              

                count = pstm.executeUpdate();
                con.close();
                if(count>0){
                    JOptionPane.showMessageDialog(this, "Inserted !", "Success", JOptionPane.INFORMATION_MESSAGE);
                }

            }catch (SQLException ex) {
                Logger.getLogger(Manage_Librarians.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "ID already exists!", "Execution Alert", JOptionPane.ERROR_MESSAGE);

            }
        
          }
          
          else {JOptionPane.showMessageDialog(this, "Email not valid!", "Execution Alert", JOptionPane.ERROR_MESSAGE);}
        else {
            JOptionPane.showMessageDialog(this, "Fields must be filled!", "Execution Alert", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_Add_btnActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked

        AdminDashboard Frame = new AdminDashboard() ;
        Frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void univActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_univActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_univActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        if(!id.getText().isEmpty())   
             {
            try { 
               Connection con =  DriverManager.getConnection("jdbc:derby://localhost:1527/Library", "user1", "123" );
               PreparedStatement pstm;
               int count = 0;
               int ID= Integer.parseInt(id.getText());
               String SQL="DELETE FROM Students WHERE Stud_ID = ?";
               pstm = con.prepareStatement(SQL);
               pstm.setInt(1, ID);
               count = pstm.executeUpdate();
               con.close();
               if(count>0){
                   JOptionPane.showMessageDialog(this, "Deleted !", "Success", JOptionPane.INFORMATION_MESSAGE);    
               }
               else{JOptionPane.showMessageDialog(this, "ID doesn't exist", "Execution Alert", JOptionPane.ERROR_MESSAGE);
                    }
            }catch (SQLException ex) {
               Logger.getLogger(Manage_Librarians.class.getName()).log(Level.SEVERE, null, ex);
               }
            }
        else {
          JOptionPane.showMessageDialog(this, "ID must be filled!", "Execution Alert", JOptionPane.ERROR_MESSAGE);    
        }
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Librarians.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Librarians.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Librarians.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Librarians.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Librarians().setVisible(true);
            }
        });
    }

    
    public void FillingTable(){
    
         try {
            Connection con =  DriverManager.getConnection("jdbc:derby://localhost:1527/Library", "user1", "123" );
            String SQL = "SELECT * FROM Students";
            Statement stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);  
            ResultSet rs=stmt.executeQuery(SQL);  
            
            while(rs.next()){
                int ID= rs.getInt("Stud_ID");
                String Name = rs.getString("Stud_Name");
                String Email = rs.getString("Stud_Email");
                String Phone = rs.getString("Stud_Phone");
                int Age= rs.getInt("Stud_Age");
                String University = rs.getString("Stud_University");
                
                Object[] obj = {ID,Name,Email,Phone,Age,University};
                model = (DefaultTableModel) Table_Stud.getModel();
                model.addRow(obj);
            
            }
            con.close();
            }
        catch ( SQLException err ) {
            err.printStackTrace();
        }
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle Add_btn;
    private javax.swing.JPanel Back;
    private rojerusan.RSMaterialButtonCircle Delete;
    private rojerusan.RSTableMetro Table_Stud;
    private app.bolivia.swing.JCTextField age;
    private javax.swing.JLabel close;
    private app.bolivia.swing.JCTextField email;
    private app.bolivia.swing.JCTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSMaterialButtonCircle modify_btn;
    private app.bolivia.swing.JCTextField name;
    private app.bolivia.swing.JCTextField phone;
    private app.bolivia.swing.JCTextField univ;
    // End of variables declaration//GEN-END:variables
}
