package Project;


import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;




public class Manage_Books extends javax.swing.JFrame {

    DefaultTableModel model;
    public Manage_Books() {
        initComponents();
        getDataCat();
        FillingTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new app.bolivia.swing.JCTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Author = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Publisher = new app.bolivia.swing.JCTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        edition = new app.bolivia.swing.JCTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Add_btn = new rojerusan.RSMaterialButtonCircle();
        modify_btn = new rojerusan.RSMaterialButtonCircle();
        delete_btn = new rojerusan.RSMaterialButtonCircle();
        Title = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        pages = new app.bolivia.swing.JCTextField();
        jLabel16 = new javax.swing.JLabel();
        quantity = new app.bolivia.swing.JCTextField();
        ComboCat = new rojerusan.RSComboMetro();
        ComboSub = new rojerusan.RSComboMetro();
        date = new rojeru_san.componentes.RSDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Book = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 102));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        Back.setBackground(new java.awt.Color(0, 102, 102));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText("Back");

        javax.swing.GroupLayout BackLayout = new javax.swing.GroupLayout(Back);
        Back.setLayout(BackLayout);
        BackLayout.setHorizontalGroup(
            BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
        );
        BackLayout.setVerticalGroup(
            BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        id.setBackground(new java.awt.Color(0, 51, 51));
        id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setPlaceholder("Enter ID");
        id.setSelectionColor(new java.awt.Color(153, 153, 255));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Title:");

        Author.setBackground(new java.awt.Color(0, 51, 51));
        Author.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        Author.setForeground(new java.awt.Color(255, 255, 255));
        Author.setPlaceholder("Author");
        Author.setSelectionColor(new java.awt.Color(153, 153, 255));
        Author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Author:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book-stack.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Publisher :");

        Publisher.setBackground(new java.awt.Color(0, 51, 51));
        Publisher.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        Publisher.setForeground(new java.awt.Color(255, 255, 255));
        Publisher.setPlaceholder("Publisher");
        Publisher.setSelectionColor(new java.awt.Color(153, 153, 255));
        Publisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublisherActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Publication Date:");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Edition :");

        edition.setBackground(new java.awt.Color(0, 51, 51));
        edition.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        edition.setForeground(new java.awt.Color(255, 255, 255));
        edition.setPlaceholder("Edition");
        edition.setSelectionColor(new java.awt.Color(153, 153, 255));
        edition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editionActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Category :");

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SubCategory :");

        Add_btn.setBackground(new java.awt.Color(0, 102, 102));
        Add_btn.setText("ADD");
        Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btnActionPerformed(evt);
            }
        });

        modify_btn.setBackground(new java.awt.Color(0, 102, 102));
        modify_btn.setText("MODIFY");
        modify_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modify_btnActionPerformed(evt);
            }
        });

        delete_btn.setBackground(new java.awt.Color(0, 102, 102));
        delete_btn.setText("DELETE");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        Title.setBackground(new java.awt.Color(0, 51, 51));
        Title.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setPlaceholder("Title");
        Title.setSelectionColor(new java.awt.Color(153, 153, 255));
        Title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Number of Pages :");

        pages.setBackground(new java.awt.Color(0, 51, 51));
        pages.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        pages.setForeground(new java.awt.Color(255, 255, 255));
        pages.setPlaceholder("Number of pages");
        pages.setSelectionColor(new java.awt.Color(153, 153, 255));
        pages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagesActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Quantity:");

        quantity.setBackground(new java.awt.Color(0, 51, 51));
        quantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        quantity.setForeground(new java.awt.Color(255, 255, 255));
        quantity.setPlaceholder("Quantity");
        quantity.setSelectionColor(new java.awt.Color(153, 153, 255));
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });

        ComboCat.setColorArrow(new java.awt.Color(0, 51, 51));
        ComboCat.setColorBorde(new java.awt.Color(0, 51, 51));
        ComboCat.setColorFondo(new java.awt.Color(0, 102, 102));
        ComboCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCatActionPerformed(evt);
            }
        });

        ComboSub.setColorArrow(new java.awt.Color(0, 51, 51));
        ComboSub.setColorBorde(new java.awt.Color(0, 51, 51));
        ComboSub.setColorFondo(new java.awt.Color(0, 102, 102));

        date.setColorBackground(new java.awt.Color(0, 102, 102));
        date.setColorButtonHover(new java.awt.Color(0, 102, 102));
        date.setColorForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(Author, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
                                .addGap(173, 173, 173))
                            .addComponent(jLabel5)
                            .addComponent(Publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(pages, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(jLabel16)
                                    .addComponent(ComboCat, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(ComboSub, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addComponent(jLabel9)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(edition, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modify_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Publisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel13)
                        .addGap(154, 154, 154)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(edition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modify_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(359, 359, 359))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Books_26px.png"))); // NOI18N
        jLabel2.setText("List of Books");

        close.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        Table_Book.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Author", "Publisher", "Edition", "Category", "SubCategory", "Num_Pages", "Quantity", "Pub_Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table_Book.setColorBackgoundHead(new java.awt.Color(0, 102, 102));
        Table_Book.setColorFilasForeground1(new java.awt.Color(204, 0, 204));
        Table_Book.setColorFilasForeground2(new java.awt.Color(204, 0, 204));
        Table_Book.setColorSelBackgound(new java.awt.Color(204, 0, 204));
        Table_Book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_BookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Book);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close))
                .addGap(266, 266, 266))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1396, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void Table_BookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_BookMouseClicked
       int rowNo = Table_Book.getSelectedRow();
       TableModel model = Table_Book.getModel();
       id.setText(model.getValueAt(rowNo, 0).toString());
       Title.setText(model.getValueAt(rowNo, 1).toString());
       Author.setText(model.getValueAt(rowNo, 2).toString());
       Publisher.setText(model.getValueAt(rowNo, 3).toString());
       edition.setText(model.getValueAt(rowNo, 4).toString());
       pages.setText(model.getValueAt(rowNo, 7).toString());
       quantity.setText(model.getValueAt(rowNo, 8).toString());
       date.setDatoFecha((Date) model.getValueAt(rowNo, 9));
    }//GEN-LAST:event_Table_BookMouseClicked

    private void pagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagesActionPerformed

    private void TitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitleActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        if(!id.getText().isEmpty())   
             {
            try { 
               Connection con =  DriverManager.getConnection("jdbc:derby://localhost:1527/Library", "user1", "123" );
               PreparedStatement pstm;
               int count = 0;
               int ID= Integer.parseInt(id.getText());
               String SQL="DELETE FROM Book WHERE Book_ID = ?";
               pstm = con.prepareStatement(SQL);
               pstm.setInt(1, ID);
               count = pstm.executeUpdate();
               con.close();
               if(count>0){
                   JOptionPane.showMessageDialog(this, "Deleted !", "Success", JOptionPane.INFORMATION_MESSAGE);    
               }
               else{JOptionPane.showMessageDialog(this, "ID doesn't exist", "Execution Alert", JOptionPane.ERROR_MESSAGE);
                    }
            }catch (SQLException ex) {
               Logger.getLogger(Manage_Librarians.class.getName()).log(Level.SEVERE, null, ex);
               }
            }
        else {
          JOptionPane.showMessageDialog(this, "ID must be filled!", "Execution Alert", JOptionPane.ERROR_MESSAGE);    
        }
           
    }//GEN-LAST:event_delete_btnActionPerformed

             
    private void modify_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modify_btnActionPerformed
   if(!id.getText().isEmpty() && !Title.getText().isEmpty() && !Author.getText().isEmpty() &&!Publisher.getText().isEmpty() && !edition.getText().isEmpty()  && !pages.getText().isEmpty() && !quantity.getText().isEmpty() )   
            {
            try { 
                PreparedStatement pstm;
                int count;
                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Library", "user1", "123" );
                count = 0;
                String Cat= ComboCat.getSelectedItem().toString();
                String Sub= ComboSub.getSelectedItem().toString();
                int ID= Integer.parseInt(id.getText());
                String title = Title.getText();
                String auth = Author.getText();
                String pub = Publisher.getText();
                String ed = edition.getText();
                int Pages= Integer.parseInt(pages.getText());
                int Quan= Integer.parseInt(quantity.getText());
                  
                Date PD= (Date) date.getDatoFecha();
                 long l1 = PD.getTime();
              
                 java.sql.Date pd = new java.sql.Date(l1);
              
                String SQL= "UPDATE Book SET Book_ID=?,Title=?,Author=?,Publisher=?,Edition=?,Category=?,SubCategory=?,Num_pages=?,Quantity=? ,Pub_Date=? WHERE Book_ID=?";
                pstm = con.prepareStatement(SQL);
                pstm.setInt(1, ID);
                pstm.setString(2, title);
                pstm.setString(3, auth);
                pstm.setString(4, pub);
                pstm.setString(5, ed);
                pstm.setString(6, Cat);
                pstm.setString(7, Sub);
                pstm.setInt(8, Pages);
                pstm.setInt(9, Quan);
                pstm.setDate(10, pd);
                 pstm.setInt(11, ID);
                count = pstm.executeUpdate();
                if(count>0){
                   JOptionPane.showMessageDialog(this, "Updated !", "Success", JOptionPane.INFORMATION_MESSAGE);    
               }
                else {
                JOptionPane.showMessageDialog(this, "ID doesn't exist", "Execution Alert", JOptionPane.ERROR_MESSAGE);
                }

            }catch (SQLException ex) {
               Logger.getLogger(Manage_Librarians.class.getName()).log(Level.SEVERE, null, ex);
               }
            }
        else {
          JOptionPane.showMessageDialog(this, "Fields must be filled!", "Execution Alert", JOptionPane.ERROR_MESSAGE);    
   }
           

    }//GEN-LAST:event_modify_btnActionPerformed

    private void Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btnActionPerformed
      
        
         if(!id.getText().isEmpty() && !Title.getText().isEmpty() && !Author.getText().isEmpty() &&!Publisher.getText().isEmpty() && !edition.getText().isEmpty()  && !pages.getText().isEmpty() && !quantity.getText().isEmpty())   
             {
            try { 
                 String Cat= ComboCat.getSelectedItem().toString();
                  String Sub= ComboSub.getSelectedItem().toString();
                Connection con =  DriverManager.getConnection("jdbc:derby://localhost:1527/Library", "user1", "123" );
                PreparedStatement pstm;
                int count =0;
                int ID= Integer.parseInt(id.getText());
                String title = Title.getText();
                String auth = Author.getText();
                String pub = Publisher.getText();
                String ed = edition.getText();
                int Pages= Integer.parseInt(pages.getText());
                int Quan= Integer.parseInt(quantity.getText());
                Date PD= (Date) date.getDatoFecha();
                 long l1 = PD.getTime();
              
              java.sql.Date pd  = new java.sql.Date(l1);
          
               
               
                String SQL= "INSERT INTO Book VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
               
                pstm = con.prepareStatement(SQL);
                pstm.setInt(1, ID);
                pstm.setString(2, title);
                pstm.setString(3, auth);
                pstm.setString(4, pub);
                pstm.setString(5, ed);
                pstm.setString(6, Cat);
                pstm.setString(7, Sub);
                pstm.setInt(8, Pages);
                pstm.setInt(9, Quan);
                pstm.setDate(10, pd);
                pstm.setInt(11,0);
                pstm.setBoolean(12,true);
                count = pstm.executeUpdate();
                con.close();
                if(count>0){
                   JOptionPane.showMessageDialog(this, "Inserted !", "Success", JOptionPane.INFORMATION_MESSAGE);    
               }
               

            }catch (SQLException ex) {
               Logger.getLogger(Manage_Librarians.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(this, "ID already exists!", "Execution Alert", JOptionPane.ERROR_MESSAGE);

               }
            }
        else {
          JOptionPane.showMessageDialog(this, "Fields must be filled!", "Execution Alert", JOptionPane.ERROR_MESSAGE);    
        }
        
        
        
        

    }//GEN-LAST:event_Add_btnActionPerformed

    private void editionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editionActionPerformed

    private void PublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PublisherActionPerformed

    private void AuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AuthorActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked

        AdminDashboard Frame = new AdminDashboard() ;
        Frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void ComboCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCatActionPerformed
        getDataSub();
    }//GEN-LAST:event_ComboCatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Books().setVisible(true);
            }
        });
    }

    
  
   
public void getDataSub (){
            try {
            String Cat= ComboCat.getSelectedItem().toString();
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Library", "user1", "123");
            PreparedStatement pstm;
            pstm = con.prepareStatement( "select * from Category WHERE Category = ?");
                
            
            pstm.setString(1, Cat);
            ResultSet rs = pstm.executeQuery();
            ComboSub.removeAllItems();
            while (rs.next()){
                if (rs.getString("SubCategory1")!=null){
                String sub1 = rs.getString("SubCategory1");
                 ComboSub.addItem(sub1);
                }
                if (rs.getString("SubCategory2")!=null){
                String sub2 = rs.getString("SubCategory2");
                 ComboSub.addItem(sub2);
                }
                 if (rs.getString("SubCategory3")!=null){
                String sub3 = rs.getString("SubCategory3");
                 ComboSub.addItem(sub3);
                }
                 if (rs.getString("SubCategory4")!=null){
                String sub4 = rs.getString("SubCategory4");
                 ComboSub.addItem(sub4);
                }
                if (rs.getString("SubCategory1")==null && rs.getString("SubCategory2")==null && rs.getString("SubCategory3")==null && rs.getString("SubCategory4")==null){
                
                ComboSub.enableInputMethods(false);
                }
             }

            con.close();
        } catch (SQLException ex) {
                System.out.println(ex);
        }}
         
         
         

 public void getDataCat (){
            try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Library", "user1", "123");          
            Statement stm = con.createStatement();
            String SQL = "SELECT * FROM CATEGORY ";
            ResultSet rs = stm.executeQuery( SQL );
            
            while (rs.next()){
               
                 String name= rs.getString("CATEGORY");
                 ComboCat.addItem(name);
             }

            con.close();
        } catch (SQLException ex) {
                System.out.println(ex);
        }}
 
 
  public void FillingTable(){

         try {
            Connection con =  DriverManager.getConnection("jdbc:derby://localhost:1527/Library", "user1", "123" );
            String SQL = "SELECT * FROM Book";
            Statement stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);  
            ResultSet rs=stmt.executeQuery(SQL);  
            
            while(rs.next()){
                int ID= rs.getInt("Book_ID");
                String tit = rs.getString("Title");
                String auth = rs.getString("Author");
                String pub = rs.getString("Publisher");
                String ed = rs.getString("Edition");
                String cat= rs.getString("Category");
                String subcat= rs.getString("SubCategory");
                int npages= rs.getInt("Num_pages");
                int quan= rs.getInt("Quantity");
                Date pubdate= rs.getDate("Pub_Date");
                Object[] obj = {ID,tit,auth,pub,ed,cat,subcat,npages,quan,pubdate};
                model = (DefaultTableModel) Table_Book.getModel();
                model.addRow(obj);
            
            }
            con.close();
            }
        catch ( SQLException err ) {
            err.printStackTrace();
        }
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle Add_btn;
    private app.bolivia.swing.JCTextField Author;
    private javax.swing.JPanel Back;
    private rojerusan.RSComboMetro ComboCat;
    private rojerusan.RSComboMetro ComboSub;
    private app.bolivia.swing.JCTextField Publisher;
    private rojerusan.RSTableMetro Table_Book;
    private app.bolivia.swing.JCTextField Title;
    private javax.swing.JLabel close;
    private rojeru_san.componentes.RSDateChooser date;
    private rojerusan.RSMaterialButtonCircle delete_btn;
    private app.bolivia.swing.JCTextField edition;
    private app.bolivia.swing.JCTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSMaterialButtonCircle modify_btn;
    private app.bolivia.swing.JCTextField pages;
    private app.bolivia.swing.JCTextField quantity;
    // End of variables declaration//GEN-END:variables
}
